version: "3.5"

services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    build:
      context: ollama
    container_name: ollama.ollama-nvidia.dnp.dappnode.eth
  ui:
    container_name: ui.ollama-nvidia.dnp.dappnode.eth
